name: Tests

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.3" ]
        composer-dependency: [ prefer-stable ]

    name: "PHP ${{ matrix.php }} - ${{ matrix.composer-dependency }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer global update
          composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --${{ matrix.composer-dependency }}

      - name: Execute tests
        run: vendor/bin/phpunit
